spring:
  application:
    name: CourierTrackerApi
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:courier-tracker
    username: admin
    password: m!gr0s
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: @spring.profiles.active@
  security:
    user:
      name: admin
  config:
    import: optional:secrets.yaml
api:
  circumference-in-meters: 100
  interval-in-minutes: 1
  user-name: user
jwt:
  expiration-duration-in-seconds: 3600000 #1 hour
